### ISSUE TITLE
Meteostat 2.0.0

### ISSUE THREAD

**Issue by clampr** [meteostat/meteostat-python#76]
Version 2 of this library won't release any time soon. However, I want to start collecting some ideas for a successor of the current version. In the past year, _Meteostat Python_ has become the heart and the soul of Meteostat. Therefore, I want to take some time to discuss potential new features and changes.

The library was well received by the open source community and is actively used on dozens of projects. Therefore, the package's next iteration should put a strong focus on performance and stability. Also, let's try to maintain backwards-compatibility as much as possible and keep things simple.

## Roadmap

- [x] Create a `next` branch
- [ ] Define structure of interfaces
- [ ] ...
- [ ] Write tests for **everything**

## Concepts

V2 will feature a full rewrite of the library. But there'll only be little changes to the public API.

### Package Structure

For v2 I'm planning with the same package structure we already use in v1:

- `meteostat`
  - `Hourly()`: Wrapper for hourly time series
  - `Daily()`: Wrapper for daily time series
  - `Monthly()`: Wrapper for monthly time series
  - `Normals()`: Wrapper for climate normals
  - `Point()`: Interface for geo points
  - `Stations()`: Meta data for weather stations
    - `meta()`: Returns dictionary with meta data for specified station ID
    - `nearby()`: Returns list of nearby station IDs for specified coordinates
    - ...

I'm also thinking about having a single `~/.meteostat/config.json` file where global configuration can be changed. Additionally, users will be able to pass a `dict` to every class which allows individual configuration, e.g:

```py
from meteostat import Hourly

config = {
 'max_age': 3600
}

data = Hourly('10637', config=config)
```

### Examples

Daily data for closest weather station:

```py
from meteostat import Stations, Point, Daily

# Set time period
start = datetime(2018, 1, 1)
end = datetime(2018, 12, 31)

# Get closest weather station
loc = Point(49.2497, -123.1193)
station = Stations().nearby(loc, limit=1)[0]

df = Daily(station, start, end)
```

### Caching

For v2 I suggest using an SQL database for caching. Users can pass any SQLAlchemy connection and the library stores all data in dedicated SQL tables. This would allow rapid access of data on both spatial and time axis.

**That's it for now. I'll keep extending this post with more concepts in the course of the following weeks and months. Feel free to add comments and share your ideas!**

**Comment by clampr** [comment]
I'm closing this for now as most of the stuff can be done in minor releases.
